var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(city)/isletme/talepler/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1nsujaz._.js")
R.c("server/chunks/ssr/1d2u_next_dist_1o3zyfk._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0miu0z4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jhg_a8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d01urn._.js")
R.c("server/chunks/ssr/1d2u_next_dist_client_components_1z4pbn4._.js")
R.c("server/chunks/ssr/1d2u_next_dist_client_components_builtin_forbidden_0yofafx.js")
R.c("server/chunks/ssr/1d2u_next_dist_client_components_builtin_unauthorized_0xq3jkj.js")
R.c("server/chunks/ssr/1d2u_next_dist_client_components_builtin_global-error_0oddyzj.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ata58._.js")
R.c("server/chunks/ssr/_05pktnl._.js")
R.c("server/chunks/ssr/12--_space__next-internal_server_app_(city)_isletme_talepler_page_actions_1s3sqwq.js")
R.m(40463)
module.exports=R.m(40463).exports
