import Link from 'next/link';
import {notFound} from 'next/navigation';
import {cache} from 'react';
import {MapPin,ShieldCheck,Store} from 'lucide-react';
import {publishedBusiness} from '@/lib/business-server';
import {BUSINESS_CATEGORIES} from '@/lib/business-shared';
import {siteUrl} from '@/lib/site-url';
import {SafeDate} from '@/components/safe-format';
export const dynamic='force-dynamic';
const getBusiness=cache(publishedBusiness);
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props){const {slug}=await params;const b=await getBusiness(slug);if(!b)return {title:'İşletme bulunamadı',robots:{index:false,follow:false}};const url=`${await siteUrl()}/isletmeler/${b.slug}`;return {title:`${b.name} — ${b.district}`,description:b.description?.slice(0,160),alternates:{canonical:url},openGraph:{title:b.name,description:b.description?.slice(0,160),url,type:'website'}};}
export default async function Page({params}:Props){const {slug}=await params;const b=await getBusiness(slug);if(!b)notFound();const url=`${await siteUrl()}/isletmeler/${b.slug}`;
 const structured={'@context':'https://schema.org','@type':b.publicAddress?'LocalBusiness':'Organization','@id':`${url}#business`,name:b.name,url,description:b.description,...(b.publicAddress?{address:{'@type':'PostalAddress',streetAddress:b.publicAddress,addressLocality:b.district,addressRegion:'İstanbul',addressCountry:'TR'}}:{}),...(b.publicPhone?{telephone:b.publicPhone}:{}),areaServed:b.serviceDistricts.map(d=>({'@type':'AdministrativeArea',name:`${d}, İstanbul`}))};
 const safeJson=JSON.stringify(structured).replace(/</g,String.fromCharCode(92,117,48,48,51,99));
 return <article className="space-y-6"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:safeJson}}/><Link href="/isletmeler" className="text-sm text-primary">← İşletmeleri keşfet</Link><header className="panel p-6 md:p-8"><div className="flex gap-4 items-start"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-xl bg-accent text-primary"><Store size={29}/></span><div className="min-w-0"><p className="eyebrow text-primary mb-2">{BUSINESS_CATEGORIES[b.category]}</p><h1 className="page-title break-words">{b.name}</h1><p className="mt-2 text-sm text-muted-foreground">{b.branchName} · {b.district}, İstanbul</p></div></div><div className="mt-5 flex flex-wrap gap-3"><span className="status bg-accent text-accent-foreground"><ShieldCheck size={14}/>Profil sahipliği incelendi</span><span className="text-xs text-muted-foreground self-center">Profil güncellemesi: <SafeDate date={b.updatedAt} locale="tr-TR" options={{dateStyle:'medium'}}/></span></div></header>
 <div className="grid gap-6 lg:grid-cols-[1.7fr_1fr]"><div className="space-y-6">{[['İşletme hakkında',b.description],['Hizmetler ve çalışma biçimi',b.services],['Kapsam ve istisnalar',b.exclusions||'İşletme tarafından ek kapsam bilgisi belirtilmedi.']].map(([title,value])=><section key={title} className="panel p-6"><h2 className="section-title mb-4">{title}</h2><p className="text-sm leading-7 whitespace-pre-wrap break-words">{value}</p></section>)}<section className="panel p-6"><h2 className="section-title mb-3">Deneyimler ve teklifler</h2><p className="text-sm leading-7 text-muted-foreground">Bu pilot dilimde yorum, teklif ve randevu özellikleri henüz açık değildir. Bu işletme için platform tarafından hesaplanmış bir deneyim puanı bulunmuyor.</p></section></div><aside className="space-y-5"><section className="panel p-6"><h2 className="section-title mb-4">Hizmet bilgileri</h2><p className="text-sm font-medium flex gap-2 items-center"><MapPin size={16} className="text-primary"/>Hizmet verilen ilçeler</p><div className="flex flex-wrap gap-2 mt-3">{b.serviceDistricts.map(d=><span key={d} className="text-xs bg-muted px-2 py-1 rounded-md">{d}</span>)}</div>{b.publicAddress&&<div className="mt-5"><h3 className="text-sm font-medium">İş yeri adresi</h3><p className="text-sm text-muted-foreground mt-2 break-words">{b.publicAddress}</p></div>}{b.hoursText&&<div className="mt-5"><h3 className="text-sm font-medium">Çalışma / görüşme saatleri</h3><p className="text-sm text-muted-foreground mt-2">{b.hoursText}</p></div>}{b.publicPhone&&<div className="mt-5"><h3 className="text-sm font-medium mb-2">İş telefonu</h3><a className="text-primary text-sm underline" href={`tel:${b.publicPhone.replace(/[^+0-9]/g,'')}`}><span suppressHydrationWarning>{b.publicPhone}</span></a></div>}{b.website&&<a className="btn-light mt-5 w-full" href={b.website} target="_blank" rel="noopener noreferrer nofollow ugc">Kurumsal internet sitesi ↗</a>}</section><section className="rounded-xl bg-accent text-accent-foreground p-5 text-sm leading-6"><ShieldCheck size={22}/><h2 className="font-semibold mt-3">Bu etiket neyi gösterir?</h2><p className="mt-2">Profili yöneten kişinin işletmeyi temsil yetkisi platform tarafından incelenmiştir. Bu, belediye onayı veya hizmet kalitesi garantisi değildir.</p>{b.verifiedAt&&<p className="text-xs mt-3">Son kontrol: <SafeDate date={b.verifiedAt} locale="tr-TR" options={{dateStyle:'medium'}}/></p>}<p className="mt-3">Hizmet bilgileri işletme tarafından sağlanır. Karar vermeden önce güncel kapsam ve koşulları işletmeyle teyit edin.</p></section></aside></div></article>;
}
