var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(city)/taleplerim/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__071cw-p._.js")
R.c("server/chunks/ssr/1d2u_next_dist_1o3zyfk._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0miu0z4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jhg_a8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d01urn._.js")
R.c("server/chunks/ssr/1d2u_next_dist_client_components_1z4pbn4._.js")
R.c("server/chunks/ssr/1d2u_next_dist_client_components_builtin_forbidden_0yofafx.js")
R.c("server/chunks/ssr/1d2u_next_dist_client_components_builtin_unauthorized_0xq3jkj.js")
R.c("server/chunks/ssr/1d2u_next_dist_client_components_builtin_global-error_0oddyzj.js")
R.c("server/chunks/ssr/[root-of-the-server]__04ata58._.js")
R.c("server/chunks/ssr/_05pktnl._.js")
R.c("server/chunks/ssr/12--_space__next-internal_server_app_(city)_taleplerim_[id]_page_actions_1-ra04g.js")
R.m(7548)
module.exports=R.m(7548).exports
