// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/akademi" | "/basvuru/yeni" | "/basvurular" | "/basvurular/[id]" | "/duyurular" | "/isletme" | "/isletme/talepler" | "/isletmeler" | "/isletmeler/[slug]" | "/login" | "/platform/isletmeler" | "/profil" | "/signup" | "/talep/yeni" | "/taleplerim" | "/taleplerim/[id]" | "/turizm" | "/yonetim"
type AppRouteHandlerRoutes = "/api/announcements" | "/api/announcements/[id]" | "/api/auth/[...nextauth]" | "/api/auth/login" | "/api/business-requests" | "/api/business-requests/[id]/offer" | "/api/businesses" | "/api/businesses/[id]" | "/api/dashboard" | "/api/directory" | "/api/directory/[slug]" | "/api/platform/businesses" | "/api/platform/businesses/[id]" | "/api/profile" | "/api/requests" | "/api/requests/[id]" | "/api/signup" | "/api/tickets" | "/api/tickets/[id]" | "/api/upload/complete" | "/api/upload/presigned"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/akademi": {}
  "/api/announcements": {}
  "/api/announcements/[id]": { "id": string; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/login": {}
  "/api/business-requests": {}
  "/api/business-requests/[id]/offer": { "id": string; }
  "/api/businesses": {}
  "/api/businesses/[id]": { "id": string; }
  "/api/dashboard": {}
  "/api/directory": {}
  "/api/directory/[slug]": { "slug": string; }
  "/api/platform/businesses": {}
  "/api/platform/businesses/[id]": { "id": string; }
  "/api/profile": {}
  "/api/requests": {}
  "/api/requests/[id]": { "id": string; }
  "/api/signup": {}
  "/api/tickets": {}
  "/api/tickets/[id]": { "id": string; }
  "/api/upload/complete": {}
  "/api/upload/presigned": {}
  "/basvuru/yeni": {}
  "/basvurular": {}
  "/basvurular/[id]": { "id": string; }
  "/duyurular": {}
  "/isletme": {}
  "/isletme/talepler": {}
  "/isletmeler": {}
  "/isletmeler/[slug]": { "slug": string; }
  "/login": {}
  "/platform/isletmeler": {}
  "/profil": {}
  "/signup": {}
  "/talep/yeni": {}
  "/taleplerim": {}
  "/taleplerim/[id]": { "id": string; }
  "/turizm": {}
  "/yonetim": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
