// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(city)/akademi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/akademi">> = Specific
  const handler = {} as typeof import("../../app/(city)/akademi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/basvuru/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/basvuru/yeni">> = Specific
  const handler = {} as typeof import("../../app/(city)/basvuru/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/basvurular/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/basvurular/[id]">> = Specific
  const handler = {} as typeof import("../../app/(city)/basvurular/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/basvurular/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/basvurular">> = Specific
  const handler = {} as typeof import("../../app/(city)/basvurular/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/duyurular/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/duyurular">> = Specific
  const handler = {} as typeof import("../../app/(city)/duyurular/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/isletme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/isletme">> = Specific
  const handler = {} as typeof import("../../app/(city)/isletme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/isletme/talepler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/isletme/talepler">> = Specific
  const handler = {} as typeof import("../../app/(city)/isletme/talepler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/isletmeler/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/isletmeler/[slug]">> = Specific
  const handler = {} as typeof import("../../app/(city)/isletmeler/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/isletmeler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/isletmeler">> = Specific
  const handler = {} as typeof import("../../app/(city)/isletmeler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/platform/isletmeler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform/isletmeler">> = Specific
  const handler = {} as typeof import("../../app/(city)/platform/isletmeler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profil">> = Specific
  const handler = {} as typeof import("../../app/(city)/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/talep/yeni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/talep/yeni">> = Specific
  const handler = {} as typeof import("../../app/(city)/talep/yeni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/taleplerim/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/taleplerim/[id]">> = Specific
  const handler = {} as typeof import("../../app/(city)/taleplerim/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/taleplerim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/taleplerim">> = Specific
  const handler = {} as typeof import("../../app/(city)/taleplerim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/turizm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/turizm">> = Specific
  const handler = {} as typeof import("../../app/(city)/turizm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(city)/yonetim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/yonetim">> = Specific
  const handler = {} as typeof import("../../app/(city)/yonetim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/announcements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/announcements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements">> = Specific
  const handler = {} as typeof import("../../app/api/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/business-requests/[id]/offer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/business-requests/[id]/offer">> = Specific
  const handler = {} as typeof import("../../app/api/business-requests/[id]/offer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/business-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/business-requests">> = Specific
  const handler = {} as typeof import("../../app/api/business-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/businesses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/businesses/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/businesses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/businesses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/businesses">> = Specific
  const handler = {} as typeof import("../../app/api/businesses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/directory/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/directory/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/directory/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/directory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/directory">> = Specific
  const handler = {} as typeof import("../../app/api/directory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/platform/businesses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/businesses/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/platform/businesses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/platform/businesses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/businesses">> = Specific
  const handler = {} as typeof import("../../app/api/platform/businesses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/requests/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requests/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/requests/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requests">> = Specific
  const handler = {} as typeof import("../../app/api/requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/signup">> = Specific
  const handler = {} as typeof import("../../app/api/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tickets/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/tickets/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tickets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tickets">> = Specific
  const handler = {} as typeof import("../../app/api/tickets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/complete">> = Specific
  const handler = {} as typeof import("../../app/api/upload/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/presigned/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/presigned">> = Specific
  const handler = {} as typeof import("../../app/api/upload/presigned/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(city)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(city)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
