import Link from 'next/link';
import {Store,MapPin,ShieldCheck,ArrowUpRight,Search} from 'lucide-react';
import {BUSINESS_CATEGORIES} from '@/lib/business-shared';
import {DISTRICTS} from '@/lib/constants';
import {listPublicBusinesses,publishedWhere} from '@/lib/business-server';
import {prisma} from '@/lib/db';
import {siteUrl} from '@/lib/site-url';
export const dynamic='force-dynamic';
type Props={searchParams:Promise<Record<string,string|string[]|undefined>>};
export async function generateMetadata({searchParams}:Props){const p=await searchParams;const hasPublished=!!(await prisma.business.findFirst({where:publishedWhere,select:{id:true}}));return {title:'İstanbul işletmelerini keşfet',description:'İstanbul’da hizmet veren işletmelerin hizmet kapsamını, bölgelerini ve sahipliği incelenmiş profillerini keşfedin.',alternates:{canonical:`${await siteUrl()}/isletmeler`},robots:{index:hasPublished&&!Object.keys(p).length,follow:true}};}
export default async function Page({searchParams}:Props){
 const p=await searchParams;const category=typeof p.kategori==='string'&&BUSINESS_CATEGORIES[p.kategori]?p.kategori:'';const district=typeof p.ilce==='string'&&DISTRICTS.includes(p.ilce)?p.ilce:'';const q=typeof p.q==='string'?p.q.trim().slice(0,80):'';const page=Math.max(1,Math.min(10000,Math.floor(Number(p.sayfa)||1)));const result=await listPublicBusinesses({category,district,q,page});
 function pageLink(n:number){const sp=new URLSearchParams();if(category)sp.set('kategori',category);if(district)sp.set('ilce',district);if(q)sp.set('q',q);sp.set('sayfa',String(n));return `/isletmeler?${sp}`;}
 return <div className="space-y-6"><section className="rounded-xl bg-secondary text-secondary-foreground p-7 md:p-9"><p className="eyebrow text-secondary-foreground/70 mb-4">İSTANBUL’UN İŞLETMELERİ · KEŞİF PİLOTU</p><h1 className="page-title max-w-xl">İhtiyacınıza uygun işletmeyi<br className="hidden sm:block"/> daha yakından tanıyın.</h1><p className="mt-4 text-sm leading-7 text-secondary-foreground/80 max-w-2xl">Gerçek hizmet bilgileri, açık hizmet bölgeleri ve sahipliği incelenmiş profiller. Karar vermeden önce işletmenin ne sunduğunu keşfedin.</p><Link href="/isletme" className="btn mt-5">İşletmenizi ekleyin <ArrowUpRight size={16}/></Link></section>
 <form action="/isletmeler" className="panel p-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-[1.3fr_1fr_1fr_auto]"><label className="field">İşletme adı<input name="q" maxLength={80} defaultValue={q} placeholder="İşletme adıyla ara"/></label><label className="field">Hizmet kategorisi<select name="kategori" defaultValue={category}><option value="">Tüm kategoriler</option>{Object.entries(BUSINESS_CATEGORIES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field">Hizmet alınacak ilçe<select name="ilce" defaultValue={district}><option value="">Tüm İstanbul</option>{DISTRICTS.map(d=><option key={d}>{d}</option>)}</select></label><button className="btn self-end"><Search size={16}/>Ara</button></form>
 <div className="flex flex-wrap justify-between items-center gap-3"><h2 className="section-title">{category?BUSINESS_CATEGORIES[category]:'İşletmeleri keşfedin'}</h2>{(q||district||category)&&<Link href="/isletmeler" className="text-sm text-primary underline underline-offset-4">Filtreleri temizle</Link>}</div>
 {result.items.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{result.items.map(b=><Link key={b.id} href={`/isletmeler/${b.slug}`} className="panel p-5 group hover:shadow-md transition flex flex-col"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-xl bg-accent text-primary"><Store size={25}/></span><ArrowUpRight className="text-muted-foreground group-hover:text-primary" size={18}/></div><p className="text-xs text-primary mt-5">{BUSINESS_CATEGORIES[b.category]}</p><h3 className="text-lg font-semibold mt-1 break-words">{b.name}</h3><p className="text-xs text-muted-foreground mt-1">{b.branchName}</p><p className="mt-4 text-sm leading-6 text-muted-foreground line-clamp-3">{b.description}</p><div className="mt-auto pt-5 flex flex-wrap gap-3 text-xs"><span className="flex items-center gap-1"><MapPin size={14}/>{b.district}</span><span className="flex items-center gap-1 text-accent-foreground"><ShieldCheck size={14}/>Sahiplik incelendi</span></div></Link>)}</div>:<section className="panel py-12 px-6 text-center"><Store className="mx-auto text-primary mb-4" size={34}/><h2 className="section-title">{q||district||category?'Bu aramada yayımlanmış işletme bulunamadı.':'İlk işletmeler için başvurular açık.'}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground max-w-xl mx-auto">{q||district||category?'Filtreleri değiştirebilir veya daha sonra yeniden bakabilirsiniz.':'Sahiplik incelemesi tamamlanan gerçek işletmeler burada yer alacak. Henüz onaylanmamış kayıtlar ve örnek işletmeler gösterilmez.'}</p><Link href="/isletme" className="btn-light mt-5">İşletme başvurusu</Link></section>}
 {(page>1||result.hasNext)&&<nav aria-label="İşletme sayfaları" className="flex items-center justify-center gap-4">{page>1&&<Link className="btn-light" href={pageLink(page-1)}>Önceki</Link>}<span className="text-sm">Sayfa {page}</span>{result.hasNext&&<Link className="btn-light" href={pageLink(page+1)}>Sonraki</Link>}</nav>}
 <aside className="rounded-xl bg-accent p-5 text-accent-foreground text-sm leading-6"><div className="flex gap-2 items-center font-semibold"><ShieldCheck size={18}/>Bilgiye dayalı seçim, açık sınırlar</div><p className="mt-2">Sahiplik incelemesi işletmenin temsil yetkisine ilişkindir; hizmet kalitesini garanti etmez. Teklif, randevu ve deneyim yorumları bu pilot dilimde henüz açılmadı.</p></aside></div>;
}
