'use client';
import {useEffect,useState} from 'react';
import {Plus,Megaphone,MapPin,CalendarDays,Droplets,Zap,Construction,ChevronDown,ChevronUp,Trash2,Pencil,Save,Loader2,X} from 'lucide-react';
import {DISTRICTS,TYPES} from '@/lib/constants';
import {request,jsonBody} from '@/lib/client';
import {ErrorBox,Loading,Empty} from './city-ui';
import {SafeDate} from './safe-format';
function localInput(value:string){return new Date(new Date(value).getTime()+10800000).toISOString().slice(0,16);}
export default function Announcements({admin,initialDistrict,initialOpen='',initialManage=false}:{admin:boolean;initialDistrict:string;initialOpen?:string;initialManage?:boolean}){const [district,setDistrict]=useState(initialDistrict);const [type,setType]=useState('');const [manage,setManage]=useState(initialManage&&admin);const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(initialOpen);const [form,setForm]=useState<any>(initialManage?{}:null);const [busy,setBusy]=useState(false);const [reload,setReload]=useState(0);const [success,setSuccess]=useState('');const [deleting,setDeleting]=useState('');
 useEffect(()=>{setDistrict(initialDistrict);},[initialDistrict]);
 useEffect(()=>{let live=true;setLoading(true);request(`/api/announcements?district=${encodeURIComponent(district)}&manage=${manage}`).then((d:any)=>{if(live){setRows(d??[]);setError('');}}).catch((e:Error)=>{console.error(e);if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[district,manage,reload]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await request(form?.id?`/api/announcements/${form.id}`:'/api/announcements',{method:form?.id?'PATCH':'POST',...jsonBody({title:f.get('title'),content:f.get('content'),district:f.get('district'),type:f.get('type'),startDate:new Date(`${f.get('startDate')}:00+03:00`).toISOString(),endDate:new Date(`${f.get('endDate')}:00+03:00`).toISOString()})});setForm(null);setManage(true);setSuccess('Duyuru kaydedildi.');setReload((v)=>v+1);}catch(e){console.error(e);setError(e instanceof Error?e.message:'Duyuru kaydedilemedi.');}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);setError('');try{await request(`/api/announcements/${id}`,{method:'DELETE'});setDeleting('');setSuccess('Duyuru silindi.');setReload((v)=>v+1);}catch(e){console.error(e);setError(e instanceof Error?e.message:'Duyuru silinemedi.');}finally{setBusy(false);}}
 const filtered=rows.filter((a:any)=>!type||a.type===type);
 return <div><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><h1 className="page-title">Şehrinden haberdar ol.</h1><p className="mt-2 text-sm text-muted-foreground">Mahallendeki çalışmalar, kesintiler ve etkinlikler tek bir yerde.</p></div>{admin&&<button className="btn" onClick={()=>{setForm({});setSuccess('');}}><Plus size={16}/>Duyuru oluştur</button>}</div><ErrorBox message={error}/>{success&&<p role="status" className="mb-5 rounded-lg bg-chart-4/10 p-4 text-sm text-chart-4">{success}</p>}
 {admin&&form&&<form onSubmit={save} className="panel mb-6 space-y-4 p-6"><div className="flex items-center justify-between"><h2 className="section-title">{form?.id?'Duyuruyu düzenle':'Yeni duyuru'}</h2><button type="button" aria-label="Formu kapat" onClick={()=>setForm(null)} className="btn-light !p-2"><X size={17}/></button></div><fieldset disabled={busy} key={form?.id??'new'} className="space-y-4"><label className="field">Başlık<input name="title" minLength={5} maxLength={140} required defaultValue={form?.title??''}/></label><label className="field">Duyuru metni<textarea name="content" minLength={10} maxLength={5000} rows={4} required defaultValue={form?.content??''}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="field">İlçe<select name="district" defaultValue={form?.district??district}><option>Tüm İstanbul</option>{DISTRICTS.map((d)=><option key={d}>{d}</option>)}</select></label><label className="field">Duyuru türü<select name="type" defaultValue={form?.type??'GENERAL'}>{Object.entries(TYPES).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label className="field">Başlangıç (Türkiye saati)<input type="datetime-local" name="startDate" required defaultValue={form?.startDate?localInput(form.startDate):''}/></label><label className="field">Bitiş (Türkiye saati)<input type="datetime-local" name="endDate" required defaultValue={form?.endDate?localInput(form.endDate):''}/></label></div><p className="text-xs text-muted-foreground">Duyuru, başlangıç ve bitiş tarihleri arasında seçilen ilçede görüntülenir.</p><button disabled={busy} className="btn">{busy?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Duyuruyu kaydet</button></fieldset></form>}
 <div className="panel mb-5 flex flex-wrap items-center gap-3 p-4"><MapPin size={19} className="text-primary"/><select aria-label="İlçe seç" value={district} onChange={(e)=>setDistrict(e.target.value)} className="w-auto" disabled={manage}>{DISTRICTS.map((d)=><option key={d}>{d}</option>)}</select><select aria-label="Duyuru türüne göre filtrele" value={type} onChange={(e)=>setType(e.target.value)} className="w-auto"><option value="">Tüm duyurular</option>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{admin&&<label className="ml-auto flex items-center gap-2 text-xs"><input type="checkbox" className="h-4 w-4 accent-primary" checked={manage} onChange={(e)=>setManage(e.target.checked)}/>Tüm duyuruları yönet</label>}</div>
 {loading?<Loading/>:filtered.length?<div className="grid gap-4 lg:grid-cols-2">{filtered.map((a:any)=>{const Icon=a.type==='WATER_OUTAGE'?Droplets:a.type==='ELECTRICITY_OUTAGE'?Zap:a.type==='ROAD_WORK'?Construction:a.type==='EVENT'?CalendarDays:Megaphone;const expanded=open===a.id;return <article key={a.id} className="panel self-start p-5"><div className="mb-4 flex items-center justify-between"><span className="flex items-center gap-2 text-xs font-medium text-primary"><span className="grid h-9 w-9 place-items-center rounded-lg bg-accent"><Icon size={18}/></span>{TYPES[a.type]}</span>{a.isDemo&&<span className="rounded-full bg-chart-3/10 px-2.5 py-1 text-[10px] text-chart-3">Örnek duyuru</span>}</div><h2 className="text-base font-semibold">{a.title}</h2><p className={`mt-3 whitespace-pre-wrap text-sm leading-relaxed text-muted-foreground ${expanded?'':'line-clamp-2'}`}>{a.content}</p><div className="mt-4 flex flex-wrap items-center gap-3 text-[10px] text-muted-foreground"><span className="flex items-center gap-1"><MapPin size={12}/>{a.district}</span><span className="flex items-center gap-1"><CalendarDays size={12}/><SafeDate date={a.startDate} locale="tr-TR" options={{day:'numeric',month:'short',year:'numeric'}}/></span></div>{expanded&&<div className="mt-4 rounded-lg bg-muted p-3 text-xs"><p>Başlangıç: <SafeDate date={a.startDate} locale="tr-TR" options={{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Istanbul'}}/></p><p className="mt-2">Bitiş: <SafeDate date={a.endDate} locale="tr-TR" options={{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Istanbul'}}/></p>{a.isDemo&&<p className="mt-3 text-chart-3">Tanıtım amaçlı örnek içeriktir; gerçek kesinti veya etkinlik bildirimi değildir.</p>}</div>}<div className="mt-4 flex items-center gap-2"><button className="btn-light !min-h-8 !px-3 !py-2 !text-[11px]" onClick={()=>setOpen(expanded?'':a.id)}>{expanded?'Daralt':'Detayları gör'}{expanded?<ChevronUp size={13}/>:<ChevronDown size={13}/>}</button>{admin&&manage&&<><button aria-label={`${a.title} duyurusunu düzenle`} onClick={()=>{setForm(a);window.scrollTo({top:0,behavior:'smooth'});}} className="btn-light ml-auto !p-2"><Pencil size={14}/></button><button aria-label={`${a.title} duyurusunu sil`} onClick={()=>setDeleting(a.id)} className="rounded-lg bg-destructive/10 p-2.5 text-destructive"><Trash2 size={14}/></button></>}</div>{deleting===a.id&&<div className="mt-4 rounded-lg bg-destructive/5 p-3"><p className="mb-3 text-xs">Bu duyuruyu kalıcı olarak silmek istiyor musunuz?</p><div className="flex gap-2"><button disabled={busy} onClick={()=>remove(a.id)} className="btn !bg-destructive !text-xs">Evet, sil</button><button className="btn-light !text-xs" onClick={()=>setDeleting('')}>Vazgeç</button></div></div>}</article>;})}</div>:<div className="panel"><Empty title="Güncel duyuru bulunmuyor" description="Farklı bir ilçe veya duyuru türü seçebilir, yeni duyurular için tekrar ziyaret edebilirsin."/></div>}</div>;
}
