'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Plus,Store,ShieldCheck,ArrowRight} from 'lucide-react';
import {BusinessForm,ManagedBusiness,BUSINESS_CATEGORIES,BUSINESS_STATUSES,emptyBusiness} from '@/lib/business-shared';
import {DISTRICTS} from '@/lib/constants';
import {jsonBody,request} from '@/lib/client';
import {ErrorBox,Loading} from './city-ui';
import {SafeDate} from './safe-format';
const labels:Record<string,string>={CREATE:'Kayıt',SAVE:'Güncelleme',SUBMIT:'İncelemeye gönderim',WITHDRAW:'Yayından çekme',APPROVE:'Onay',CHANGES:'Düzeltme isteği',SUSPEND:'Yayın durdurma'};
export default function BusinessManager(){
 const [items,setItems]=useState<ManagedBusiness[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[editor,setEditor]=useState<ManagedBusiness|'new'|null>(null);
 async function load(){setLoading(true);try{setItems(await request('/api/businesses'));}catch(e){console.error(e);setError(e instanceof Error?e.message:'Kayıtlar yüklenemedi.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-primary mb-2">İŞLETMENİZ İÇİN DİJİTAL BİR VİTRİN</p><h1 className="page-title">İşletme panelim</h1><p className="text-sm text-muted-foreground mt-2">Bilgilerinizi hazırlayın, sahiplik incelemesinden sonra keşfe açılın.</p></div><Link href="/isletmeler" className="btn-light">İşletmeleri keşfet <ArrowRight size={16}/></Link></div>
 <div className="panel p-5 flex items-start gap-3"><ShieldCheck className="text-primary shrink-0" size={22}/><p className="text-sm leading-6">Profiller yayın öncesinde incelenir. Sahiplik kontrolü bir hizmet kalitesi garantisi değildir. Özel inceleme bilgileriniz herkese açık profilinize eklenmez.</p></div>
 <ErrorBox message={error}/>{success&&<p role="status" className="rounded-lg bg-accent text-accent-foreground p-4 text-sm">{success}</p>}
 {editor!==null?<BusinessEditor key={editor==='new'?'new':editor.id} item={editor==='new'?null:editor} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);setSuccess('İşlem kaydedildi. Yayın durumu aşağıda gösteriliyor.');setError('');await load();}}/>:<><button className="btn" onClick={()=>{setEditor('new');setSuccess('');}}><Plus size={16}/>İşletme başvurusu oluştur</button>{loading?<Loading/>:items.length===0?<section className="panel p-8 text-center"><Store size={32} className="mx-auto text-primary mb-4"/><h2 className="section-title">İlk işletme profilinizi hazırlayın</h2><p className="text-sm text-muted-foreground mt-2">Gerçek hizmetleriniz, hizmet bölgeleriniz ve işletme yetki beyanınızla başlayın. Pilot sınırı hesap başına 5 kayıttır.</p></section>:<div className="grid gap-4">{items.map(item=><section key={item.id} className="panel p-5"><div className="flex flex-wrap justify-between gap-3"><div><span className="status bg-accent text-accent-foreground">{BUSINESS_STATUSES[item.status]}</span><h2 className="section-title mt-3">{item.name}</h2><p className="text-sm text-muted-foreground mt-1">{item.branchName} · {item.district} · {BUSINESS_CATEGORIES[item.category]}</p></div><div className="flex items-start gap-2">{item.status==='PUBLISHED'&&item.slug&&<Link className="btn-light" href={`/isletmeler/${item.slug}`}>Profili gör</Link>}<button disabled={item.status==='SUSPENDED'} className="btn-light" onClick={()=>{setEditor(item);setSuccess('');}}>Düzenle</button></div></div>{item.reviewMessage&&<p className="mt-4 p-3 rounded-lg bg-muted text-sm whitespace-pre-wrap">İnceleme notu: {item.reviewMessage}</p>}<details className="mt-4 text-sm"><summary className="cursor-pointer text-muted-foreground">Son işlemler</summary><ul className="mt-3 space-y-3">{item.events.map(e=><li key={e.id}><span className="font-medium">{labels[e.action]??'İşlem'}</span> · <SafeDate date={e.createdAt} locale="tr-TR" options={{dateStyle:'short'}}/><p className="text-muted-foreground whitespace-pre-wrap">{e.message}</p></li>)}</ul></details></section>)}</div>}</>}
 </div>;
}
function BusinessEditor({item,onClose,onSaved}:{item:ManagedBusiness|null;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [form,setForm]=useState<BusinessForm>(item?{...item}:emptyBusiness),[attested,setAttested]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function field(key:keyof BusinessForm,value:string){setForm(f=>({...f,[key]:value}));}
 async function save(action:'save'|'submit'|'withdraw'){setBusy(true);setError('');try{await request(item?`/api/businesses/${item.id}`:'/api/businesses',{method:item?'PATCH':'POST',...jsonBody({...form,attested,...(item?{action,revision:item.revision}:{submit:action==='submit'})})});await onSaved();}catch(e){console.error(e);setError(e instanceof Error?e.message:'Kayıt tamamlanamadı.');}finally{setBusy(false);}}
 const text=(key:keyof BusinessForm,label:string,required=false,minLength?:number,maxLength=300)=><label className="field" key={key}><span>{label}{required?' *':''}</span><input required={required} minLength={minLength} maxLength={maxLength} value={String(form[key])} onChange={e=>field(key,e.target.value)}/></label>;
 const area=(key:keyof BusinessForm,label:string,minLength:number,maxLength:number)=><label className="field" key={key}><span>{label}{minLength>0?' *':''}</span><textarea rows={4} required={minLength>0} minLength={minLength} maxLength={maxLength} value={String(form[key])} onChange={e=>field(key,e.target.value)}/><span className="text-xs text-muted-foreground">{minLength>0?`En az ${minLength}, en fazla ${maxLength} karakter.`:`En fazla ${maxLength} karakter.`}</span></label>;
 return <form className="panel p-5 md:p-7 space-y-6" onSubmit={e=>{e.preventDefault();void save('submit');}}><div className="flex justify-between gap-3"><h2 className="section-title">{item?'Profil bilgilerini düzenle':'Yeni işletme başvurusu'}</h2><button type="button" disabled={busy} className="btn-light" onClick={onClose}>Vazgeç</button></div><ErrorBox message={error}/>{item?.status==='PUBLISHED'&&<p className="bg-accent text-accent-foreground p-4 rounded-lg text-sm">Değişiklik kaydetmek mevcut profili yayından kaldırır. Yeni bilgiler tekrar incelenip onaylandığında profil aynı adresinde açılır.</p>}
 <fieldset disabled={busy} className="space-y-5"><legend className="font-semibold mb-4">Herkese açık profil bilgileri</legend><p className="text-sm text-muted-foreground">Yalnızca paylaşma hakkına sahip olduğunuz işletme bilgilerini yazın. Ev adresinizi, çocuk bilgilerini veya müşteri bilgilerini eklemeyin. Yıldızlı alanlar taslak kaydı için de gereklidir.</p><div className="grid sm:grid-cols-2 gap-4">{text('name','İşletme adı',true,2,120)}{text('branchName','Şube adı',true,2,80)}<label className="field">Kategori *<select value={form.category} onChange={e=>field('category',e.target.value)}>{Object.entries(BUSINESS_CATEGORIES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field">İşletmenin bulunduğu ilçe *<select value={form.district} onChange={e=>field('district',e.target.value)}>{DISTRICTS.map(d=><option key={d}>{d}</option>)}</select></label></div>
 {area('description','İşletmenizi tanıtın',80,2400)}{area('services','Sunduğunuz hizmetler ve çalışma biçimi',20,1600)}{area('exclusions','Kapsam dışında kalan işler ve koşullar',0,800)}
 <fieldset><legend className="text-sm font-medium mb-3">Hizmet verdiğiniz ilçeler * — en az bir ilçe</legend><div className="grid grid-cols-2 md:grid-cols-3 gap-2 max-h-56 overflow-y-auto rounded-lg bg-muted p-3">{DISTRICTS.map(d=><label key={d} className="flex gap-2 items-center text-xs py-1"><input type="checkbox" className="!w-4 !h-4" checked={form.serviceDistricts.includes(d)} onChange={e=>setForm(f=>({...f,serviceDistricts:e.target.checked?[...f.serviceDistricts,d]:f.serviceDistricts.filter(v=>v!==d)}))}/>{d}</label>)}</div></fieldset>
 <div className="grid sm:grid-cols-2 gap-4">{text('publicAddress','Yayımlanabilir iş yeri adresi')}{text('publicPhone','Herkese açık iş telefonu',false,undefined,30)}{text('website','Kurumsal internet sitesi (https://)')}{text('hoursText','Çalışma saatleri / görüşme koşulları')}</div></fieldset>
 <fieldset disabled={busy} className="rounded-xl bg-muted p-5 space-y-4"><legend className="font-semibold px-1">Özel sahiplik incelemesi</legend><p className="text-sm text-muted-foreground">Bu bölüm yalnızca siz ve yetkili platform inceleyicileri tarafından görülür. Şifre, kimlik numarası veya belge görüntüsü yazmayın.</p>{text('verificationContact','Yetkiliye ulaşılabilecek kurumsal e-posta veya telefon',true,8,240)}{area('ownershipStatement','İşletmeyle ilişkiniz ve yetkinizin nasıl teyit edilebileceği',30,1600)}<label className="flex items-start gap-3 text-sm leading-6"><input className="!w-4 !h-4 mt-1 shrink-0" type="checkbox" required checked={attested} onChange={e=>setAttested(e.target.checked)}/>Bu işletmeyi temsil etmeye ve bu bilgileri yayımlamaya yetkili olduğumu; bilgilerin doğru olduğunu beyan ediyorum. Bu beyan tek başına sahiplik doğrulaması değildir.</label></fieldset>
 <div className="flex flex-wrap gap-3"><button className="btn" disabled={busy}>{busy?'Kaydediliyor…':'İncelemeye gönder'}</button><button type="button" className="btn-light" disabled={busy} onClick={()=>void save('save')}>Taslak olarak kaydet</button>{item&&<button type="button" className="btn-light text-destructive" disabled={busy} onClick={()=>void save('withdraw')}>Yayından / incelemeden çek</button>}</div><p className="text-xs text-muted-foreground">Sahiplik incelemesi insan tarafından yapılır; otomatik yayın veya onay garantisi yoktur.</p>
 </form>;
}
