'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useState} from 'react';
import {signOut} from 'next-auth/react';
import {LayoutDashboard,FilePlus2,Files,Megaphone,Store,Compass,GraduationCap,MapPin,Bell,Search,Menu,X,ArrowUpRight,LogOut,ChevronDown,Building2,Leaf,ShieldCheck,UserRound,HandshakeIcon,PlusCircle,Inbox,CalendarCheck,Users} from 'lucide-react';
import {DISTRICTS,ROLES} from '@/lib/constants';
export type Viewer={id:string;name:string;email:string;role:string;district:string;isPlatformAdmin?:boolean}|null;
const nav=[{href:'/',label:'Genel Bakış',icon:LayoutDashboard},{href:'/basvuru/yeni',label:'Yeni Başvuru',icon:FilePlus2},{href:'/basvurular',label:'Başvurularım',icon:Files},{href:'/duyurular',label:'Duyurular',icon:Megaphone}];
export function Brand(){return <Link href="/" className="flex items-center gap-3" aria-label="İstanbul Akıllı Şehir ana sayfa"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Building2 size={25}/></span><span><span className="block text-lg font-bold tracking-[.09em] leading-tight">İSTANBUL</span><span className="block text-[9px] tracking-[.25em] opacity-65 mt-1">AKILLI ŞEHİR</span></span></Link>;}
export default function CityShell({user,children}:{user:Viewer;children:React.ReactNode}){const path=usePathname();const router=useRouter();const [mobile,setMobile]=useState(false);const [query,setQuery]=useState('');const admin=user?.role==='MUNICIPAL_ADMIN';
 return <div className="min-h-screen"><button aria-label="Menüyü aç" onClick={()=>setMobile(true)} className="fixed top-5 left-4 z-40 rounded-lg bg-card p-2 shadow md:hidden"><Menu size={20}/></button>{mobile&&<button aria-label="Menüyü kapat" className="fixed inset-0 z-40 bg-secondary/40 md:hidden" onClick={()=>setMobile(false)}/>}
 <aside className={`fixed inset-y-0 left-0 z-50 flex w-[236px] flex-col overflow-y-auto bg-secondary text-secondary-foreground transition-transform md:translate-x-0 ${mobile?'translate-x-0':'-translate-x-full'}`}><div className="px-6 pb-9 pt-8"><Brand/><button onClick={()=>setMobile(false)} className="absolute right-2 top-2 p-2 md:hidden" aria-label="Kapat"><X size={16}/></button></div><div className="px-6 mb-3 eyebrow text-secondary-foreground/40">ŞEHİR HİZMETLERİ</div><nav className="space-y-1 px-3">{nav.map((n)=>{const Icon=n.icon;const active=path===n.href||(n.href==='/basvurular'&&path.startsWith('/basvurular/'));return <Link key={n.href} href={n.href} onClick={()=>setMobile(false)} className={`flex items-center gap-3 rounded-lg px-4 py-3 text-[13px] transition ${active?'bg-primary text-primary-foreground shadow-md':'text-secondary-foreground/70 hover:bg-secondary-foreground/10 hover:text-secondary-foreground'}`}><Icon size={18}/>{admin&&n.href==='/basvurular'?'Başvuru Yönetimi':n.label}{n.href==='/basvuru/yeni'&&<span className="ml-auto text-lg leading-none opacity-70">+</span>}</Link>;})}{admin&&<Link href="/yonetim" onClick={()=>setMobile(false)} className={`flex items-center gap-3 rounded-lg px-4 py-3 text-[13px] ${path==='/yonetim'?'bg-primary':'text-secondary-foreground/70 hover:bg-secondary-foreground/10'}`}><ShieldCheck size={18}/>Belediye Paneli</Link>}</nav>
 <div className="px-6 mb-3 mt-9 eyebrow text-secondary-foreground/40">ŞEHRİN EKOSİSTEMİ</div><nav className="space-y-1 px-3">{[{href:'/talep/yeni',label:'Hizmet Talebi Oluştur',icon:PlusCircle},{href:'/taleplerim',label:'Taleplerim',icon:HandshakeIcon},{href:'/isletmeler',label:'İşletmeleri Keşfet',icon:Search},{href:'/isletme',label:'İşletme Panelim',icon:Store},{href:'/isletme/talepler',label:'Gelen Talepler',icon:Inbox},{href:'/planlar',label:'Günlük Planlarım',icon:CalendarCheck},{href:'/ekip',label:'Atadığım Görevler',icon:Users},...(user?.isPlatformAdmin?[{href:'/platform/isletmeler',label:'İşletme Yayın Yönetimi',icon:ShieldCheck}]:[]),{href:'/turizm',label:'Turizm & Keşif',icon:Compass},{href:'/akademi',label:'Yapay Zekâ Akademisi',icon:GraduationCap}].map((n)=>{const Icon=n.icon;return <Link key={n.href} href={n.href} onClick={()=>setMobile(false)} className={`flex items-center gap-3 rounded-lg px-4 py-3 text-[12px] ${path===n.href?'bg-secondary-foreground/10 text-secondary-foreground':'text-secondary-foreground/60 hover:bg-secondary-foreground/5'}`}><Icon size={18}/><span>{n.label}</span>{(n.href==='/turizm'||n.href==='/akademi')&&<span className="ml-auto rounded bg-secondary-foreground/10 px-1.5 py-0.5 text-[8px]">YAKINDA</span>}</Link>;})}</nav>
 <div className="mt-auto p-4"><div className="mb-5 rounded-xl bg-secondary-foreground/[.06] p-4"><Leaf className="mb-3 text-primary" size={23}/><p className="text-[13px] font-medium">Birlikte daha iyi bir şehir.</p><p className="text-[11px] leading-relaxed mt-2 text-secondary-foreground/50">Her başvuru, İstanbul'un geleceğine bir katkı.</p><Link href="/basvuru/yeni" className="mt-3 inline-flex items-center gap-2 text-[11px] text-secondary-foreground/90">Sen de katkı sağla <ArrowUpRight size={14}/></Link></div>{user?<div className="flex items-center gap-2.5"><Link href="/profil" className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-primary/30 text-xs font-semibold">{user.name?.slice(0,2).toLocaleUpperCase('tr-TR')}</Link><Link href="/profil" className="min-w-0 flex-1"><div className="truncate text-xs font-medium">{user.name}</div><div className="mt-1 text-[10px] text-secondary-foreground/50">{ROLES[user.role]}</div></Link><button aria-label="Çıkış yap" onClick={()=>signOut({redirectTo:'/'})} className="p-2 text-secondary-foreground/60 hover:text-secondary-foreground"><LogOut size={16}/></button></div>:<Link href="/login" className="flex items-center gap-3 rounded-lg bg-secondary-foreground/10 px-3 py-3 text-xs"><UserRound size={18}/>Hesabına giriş yap<ArrowUpRight size={15} className="ml-auto"/></Link>}</div></aside>
 <div className="md:ml-[236px]"><header className="sticky top-0 z-30 bg-card/95 backdrop-blur-md shadow-sm"><div className="mx-auto flex h-[76px] max-w-[1200px] items-center justify-between gap-4 px-5 pl-16 md:px-8"><div className="hidden items-center gap-2 text-xs text-muted-foreground lg:flex"><Building2 size={14}/><span>İstanbul</span><span className="px-1 opacity-40">/</span><span className="text-foreground">Vatandaş Hizmetleri</span></div><form onSubmit={(e)=>{e.preventDefault();router.push(`/basvurular?q=${encodeURIComponent(query)}`);}} className="relative hidden max-w-[235px] flex-1 xl:block"><Search size={15} className="absolute left-3 top-3 text-muted-foreground"/><input aria-label="Başvuru ara" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Başvuru ara…" className="border-0 bg-background py-2.5 pl-9 text-xs"/></form><div className="ml-auto flex items-center gap-3"><MapPin size={16} className="text-primary"/><select aria-label="Duyuru ilçesi" className="w-28 border-0 bg-transparent p-0 text-xs font-medium md:w-32" defaultValue={user?.district??'Kadıköy'} onChange={(e)=>router.push(`/duyurular?ilce=${encodeURIComponent(e.target.value)}`)}>{DISTRICTS.map((d)=><option key={d}>{d}</option>)}</select><span className="h-6 w-px bg-border"/><Link aria-label="Duyuruları gör" href="/duyurular" className="relative rounded-lg p-2 hover:bg-muted"><Bell size={18}/><span className="absolute right-2 top-1.5 h-1.5 w-1.5 rounded-full bg-primary"/></Link>{user?<Link aria-label="Profilim" href="/profil" className="grid h-8 w-8 place-items-center rounded-full bg-accent text-xs font-bold text-primary">{user.name?.slice(0,1)}</Link>:<Link href="/signup" className="btn !min-h-8 !px-3 !py-2 !text-xs">Kayıt ol</Link>}</div></div></header><main className="mx-auto max-w-[1200px] px-5 py-7 md:px-8 md:py-8">{children}<footer className="mt-10 flex flex-wrap items-center justify-between gap-3 border-t border-border/70 py-5 text-[10px] text-muted-foreground"><span>İstanbul Akıllı Şehir · Daha yaşanabilir bir gelecek</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-1.5 rounded-full bg-primary"/>MVP · Resmî belediye sistemi değildir</span></footer></main></div></div>;
}
