'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import dynamic from 'next/dynamic';
import {ArrowRight,Plus,MapPin,Layers3,Building2,Network,Files,Clock3,CheckCircle2,TrendingUp,Construction,Bus,Trash2,Trees,MessageSquare,ChevronRight,Sparkles,Droplets,CalendarDays,Megaphone,ShieldCheck,Send,MousePointer2} from 'lucide-react';
import {HERO,CATEGORIES,TYPES} from '@/lib/constants';
import {request} from '@/lib/client';
import {type Viewer} from './city-shell';
import {Counter,Reveal,Empty,ErrorBox,Loading,Status} from './city-ui';
import {SafeDate} from './safe-format';
const CategoryChart=dynamic(()=>import('./category-chart'),{ssr:false,loading:()=> <Loading/>});
export default function Dashboard({user,adminPage=false}:{user:Viewer;adminPage?:boolean}){const [stats,setStats]=useState<any>(null);const [announcements,setAnnouncements]=useState<any[]>([]);const [error,setError]=useState('');const [imageFailed,setImageFailed]=useState(false);const [loading,setLoading]=useState(true);const admin=user?.role==='MUNICIPAL_ADMIN';
 useEffect(()=>{let live=true;(async()=>{try{const [a,s]=await Promise.all([request(`/api/announcements?district=${encodeURIComponent(user?.district??'Kadıköy')}`),user?request('/api/dashboard'):Promise.resolve(null)]);if(live){setAnnouncements(a??[]);setStats(s);}}catch(e){console.error(e);if(live)setError(e instanceof Error?e.message:'Veriler alınamadı.');}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[user?.id,user?.district]);
 const metrics=user?[{label:'Toplam başvuru',value:stats?.total??0,icon:Files,note:admin?'Tüm ilçeler':'Tüm başvurularınız',tone:'primary'},{label:'İşlemde',value:stats?.progress??0,icon:Clock3,note:'Çözüm için çalışılıyor',tone:'chart-3'},{label:'Çözülen başvuru',value:stats?.resolved??0,icon:CheckCircle2,note:'Tamamlanan talepler',tone:'chart-4'},{label:'Çözülme oranı',value:stats?.rate??0,suffix:'%',icon:TrendingUp,note:'Toplam başvurular içinde',tone:'chart-5'}]:[{label:'İstanbul’un tüm ilçeleri',value:39,icon:MapPin,note:'Avrupa’dan Anadolu’ya',tone:'primary'},{label:'Hizmet kategorisi',value:5,icon:Layers3,note:'Doğru birime, doğrudan',tone:'chart-3'},{label:'Ekosistem modülü',value:4,icon:Network,note:'Belediye + işletme keşif pilotu',tone:'chart-4'},{label:'Ortak hizmet platformu',value:1,icon:Building2,note:'Şehrinle tek noktadan bağ kur',tone:'chart-5'}];
 const services=[{category:'INFRASTRUCTURE',icon:Construction,sub:'Yol, su ve altyapı',tone:'primary'},{category:'TRANSPORT',icon:Bus,sub:'Toplu taşıma ve trafik',tone:'chart-5'},{category:'CLEANING',icon:Trash2,sub:'Temiz bir çevre',tone:'chart-3'},{category:'PARKS',icon:Trees,sub:'Daha yeşil bir şehir',tone:'chart-4'},{category:'OTHER',icon:MessageSquare,sub:'Diğer talep ve öneriler',tone:'primary'}];
 return <div><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div className="eyebrow mb-2.5 text-muted-foreground">{admin?'BELEDİYE YÖNETİM MERKEZİ':'İSTANBUL SENİNLE DAHA GÜZEL'}</div><h1 className="page-title">{adminPage?'Şehrin hizmet nabzı.':user?`Merhaba, ${user.name?.split(' ')?.[0]??'İstanbullu'}.`:'Şehrinle bağlantıda kal.'}</h1><p className="mt-2 text-[13px] text-muted-foreground">{admin?'Başvuruları yönetin, gelişmeleri paylaşın, çözümün bir parçası olun.':'Başvurularını yönet, mahallendeki gelişmeleri takip et, İstanbul’a katkı sağla.'}</p></div><Link href={admin?'/duyurular?yonetim=1':'/basvuru/yeni'} className="btn !text-xs"><Plus size={16}/>{admin?'Duyuru oluştur':'Yeni başvuru oluştur'}</Link></div><ErrorBox message={error}/>
 {!adminPage&&<Reveal><section className="relative isolate mb-6 overflow-hidden rounded-xl bg-secondary text-secondary-foreground shadow-md"><div className="absolute inset-0">{!imageFailed&&<Image unoptimized src={HERO} fill priority sizes="100vw" alt="Boğaz Köprüsü ve İstanbul manzarası" onError={()=>setImageFailed(true)} className="object-cover object-center"/>}<div className="absolute inset-0 bg-gradient-to-r from-secondary via-secondary/85 to-secondary/10"/></div><div className="relative grid min-h-[258px] content-center px-7 py-8 md:px-9"><div className="mb-4 flex items-center gap-2 text-[10px] font-medium tracking-widest text-secondary-foreground/80"><span className="h-1.5 w-1.5 rounded-full bg-primary"/>DAHA AKILLI BİR ŞEHİR, DAHA İYİ BİR YAŞAM</div><h2 className="max-w-lg text-[29px] font-semibold leading-[1.3] tracking-tight md:text-[34px]">İstanbul için,<br/>birlikte bir adım ileri.</h2><p className="mt-3 max-w-[380px] text-xs leading-[1.8] text-secondary-foreground/75">Sokağındaki bir sorundan şehrin geleceğine…<br/>Sesini duyur, çözümü takip et. Çünkü bu şehir hepimizin.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/basvuru/yeni" className="btn !min-h-9 !px-4 !py-2 !text-xs">Başvuru oluştur <ArrowRight size={15}/></Link><Link href="/duyurular" className="inline-flex items-center gap-2 rounded-lg bg-secondary-foreground/10 px-4 py-2 text-xs transition hover:bg-secondary-foreground/20">Duyuruları keşfet <ChevronRight size={14}/></Link></div></div><div className="absolute bottom-5 right-5 hidden items-center gap-1.5 rounded-full bg-secondary/35 px-3 py-1.5 text-[10px] backdrop-blur-md sm:flex"><MapPin size={12}/>İstanbul Boğazı</div></section></Reveal>}
 <div className="mb-7 grid grid-cols-2 gap-3 xl:grid-cols-4">{metrics.map((m,i)=>{const Icon=m.icon;return <Reveal key={m.label} delay={i*.06}><div className="panel relative h-full p-4 md:p-5"><div className="flex items-center justify-between gap-2"><span className="text-[11px] text-muted-foreground">{m.label}</span><span className={`grid h-8 w-8 place-items-center rounded-lg ${i===0?'bg-primary/10 text-primary':i===1?'bg-chart-3/10 text-chart-3':i===2?'bg-chart-4/10 text-chart-4':'bg-chart-5/10 text-chart-5'}`}><Icon size={16}/></span></div><div className="mt-2 text-3xl font-semibold tracking-tight">{loading&&user?'—':<Counter value={m.value}/>}<span className="text-xl">{'suffix'in m?m.suffix:''}</span></div><p className="mt-2 text-[10px] text-muted-foreground">{m.note}</p></div></Reveal>;})}</div>
 {!adminPage&&<section className="mb-7"><div className="mb-4 flex items-center justify-between"><h2 className="section-title !text-base">Sana nasıl yardımcı olabiliriz?</h2><span className="hidden text-[10px] text-muted-foreground sm:block">İhtiyacına uygun hizmeti seç</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{services.map((s,i)=>{const Icon=s.icon;return <Link key={s.category} href={`/basvuru/yeni?kategori=${s.category}`} className="panel group flex items-center gap-3 p-4 transition hover:-translate-y-1 hover:shadow-md md:block"><span className={`mb-0 inline-flex h-9 w-9 items-center justify-center rounded-lg md:mb-3 ${i===1?'bg-chart-5/10 text-chart-5':i===2?'bg-chart-3/10 text-chart-3':i===3?'bg-chart-4/10 text-chart-4':'bg-primary/10 text-primary'}`}><Icon size={19}/></span><div><h3 className="text-xs font-semibold">{CATEGORIES[s.category]}</h3><p className="mt-1.5 hidden text-[9px] text-muted-foreground lg:block">{s.sub}</p></div></Link>;})}</div></section>}
 <div className="grid gap-5 xl:grid-cols-[1.2fr_1fr]"><section className="panel overflow-hidden"><div className="flex items-center justify-between px-5 pt-5 pb-3"><h2 className="section-title !text-base">{user?'Son başvurular':'Bir başvuru, gerçek bir katkı'}</h2>{user&&<Link href="/basvurular" className="flex items-center gap-1 rounded-md bg-accent px-2.5 py-1.5 text-[10px] font-medium text-primary">Tümünü gör <ArrowRight size={12}/></Link>}</div>{user?(loading?<Loading/>:stats?.recent?.length?<div className="px-5 pb-3">{stats.recent.map((t:any)=><Link key={t.id} href={`/basvurular/${t.id}`} className="flex items-center gap-3 border-b border-border/50 py-4 last:border-0 hover:bg-muted/50"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-muted text-muted-foreground"><Files size={17}/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{t.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{t.district} · {CATEGORIES[t.category]}</p></div><Status value={t.status}/></Link>)}</div>:<Empty title="İlk başvurunla değişimi başlat" description="Oluşturduğun başvuruları ve güncel durumlarını burada takip edebilirsin."/>):<div className="px-5 pb-5"><p className="mb-4 text-[11px] leading-relaxed text-muted-foreground">Mahallendeki ihtiyaçları doğru birime ulaştırmak artık daha kolay.</p>{[{icon:MousePointer2,title:'İhtiyacını paylaş',text:'Konumunu seç, talebini yaz ve fotoğraf ekle.'},{icon:Sparkles,title:'Akıllı yönlendirmeyle zaman kazan',text:'Yapay zekâ başvurunu ilgili birime yönlendirsin.'},{icon:CheckCircle2,title:'Her adımı takip et',text:'Başvurunun durumunu ve belediye yanıtını gör.'}].map((step,i)=>{const Icon=step.icon;return <div className="flex items-center gap-4 py-3" key={step.title}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-accent text-primary"><Icon size={17}/></span><div><h3 className="text-xs font-semibold">{step.title}</h3><p className="mt-1.5 text-[10px] text-muted-foreground">{step.text}</p></div><span className="ml-auto font-mono text-xs text-muted-foreground/40">0{i+1}</span></div>;})}<Link href="/signup" className="mt-3 inline-flex items-center gap-2 rounded-lg bg-muted px-3 py-2 text-[11px] font-medium">Hemen aramıza katıl <ArrowRight size={13}/></Link></div>}</section>
 <section className="panel"><div className="flex items-center justify-between px-5 pt-5 pb-3"><h2 className="section-title !text-base">Mahallenden haberler</h2><Link href="/duyurular" className="flex items-center gap-1 rounded-md bg-accent px-2.5 py-1.5 text-[10px] font-medium text-primary">Tümünü gör <ArrowRight size={12}/></Link></div><div className="px-5 pb-4">{loading?<Loading/>:announcements.length?announcements.slice(0,3).map((a:any,i)=>{const Icon=a.type==='WATER_OUTAGE'?Droplets:a.type==='ROAD_WORK'?Construction:a.type==='EVENT'?CalendarDays:Megaphone;return <Link key={a.id} href={`/duyurular?duyuru=${a.id}`} className="flex gap-3 border-b border-border/60 py-4 last:border-0"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg ${i===0?'bg-primary/10 text-primary':i===1?'bg-chart-3/10 text-chart-3':'bg-chart-5/10 text-chart-5'}`}><Icon size={18}/></span><div className="min-w-0 flex-1"><div className="mb-1.5 flex items-center gap-2 text-[9px] text-muted-foreground"><span>{TYPES[a.type]}</span>{a.isDemo&&<span className="rounded bg-muted px-1.5 py-0.5">Örnek</span>}</div><h3 className="truncate text-xs font-semibold">{a.title}</h3><p className="mt-2 flex items-center gap-1 text-[10px] text-muted-foreground"><MapPin size={10}/>{a.district}</p></div><ChevronRight size={14} className="mt-5 text-muted-foreground"/></Link>;}):<Empty title="Güncel duyuru bulunmuyor" description="Seçtiğin ilçeye ait yeni duyurular burada yer alacak."/>}</div></section></div>
 {user&&<section className="panel mt-5 p-5"><h2 className="section-title !text-base">Kategoriye göre başvurular</h2><p className="mt-1 text-xs text-muted-foreground">{admin?'Tüm başvuruların':'Başvurularınızın'} hizmet alanlarına göre dağılımı</p><CategoryChart data={stats?.categories??[]}/></section>}
 <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-accent/70 px-5 py-4"><div className="flex items-center gap-3"><ShieldCheck size={22} className="text-primary"/><div><p className="text-xs font-medium">Senin başvurun, senin güvenli alanın.</p><p className="mt-1 text-[10px] text-muted-foreground">Paylaşımların herkese açık değildir. Yalnızca yetkili birimlerle iletişim kurarsın.</p></div></div><span className="text-[10px] font-semibold text-primary">Sosyal akış yok. Doğrudan çözüm var.</span></div></div>;
}
