'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {UserRound,Save,ShieldCheck,Loader2} from 'lucide-react';
import {Viewer} from './city-shell';
import {DISTRICTS,ROLES} from '@/lib/constants';
import {request,jsonBody} from '@/lib/client';
import {ErrorBox} from './city-ui';
export default function ProfileForm({user}:{user:Viewer}){const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setSuccess('');const f=new FormData(e.currentTarget);const password=String(f.get('newPassword')??'');try{await request('/api/profile',{method:'PATCH',...jsonBody({name:f.get('name'),district:f.get('district'),...(password?{newPassword:password,currentPassword:f.get('currentPassword')}:{})})});setSuccess('Profiliniz güncellendi.');router.refresh();}catch(e){console.error(e);setError(e instanceof Error?e.message:'Profil kaydedilemedi.');}finally{setBusy(false);}}return <div className="max-w-2xl"><h1 className="page-title">Hesabım</h1><p className="mb-7 mt-2 text-sm text-muted-foreground">Profilini, ilçeni ve güvenlik bilgilerini yönet.</p><form onSubmit={save} className="panel space-y-5 p-6"><div className="flex items-center gap-3"><UserRound className="text-primary" size={26}/><div><h2 className="text-sm font-semibold">{user?.name}</h2><p className="mt-1 text-xs text-muted-foreground">{ROLES[user?.role??'CITIZEN']}</p></div></div><label className="field">Ad soyad<input name="name" required minLength={2} maxLength={80} defaultValue={user?.name}/></label><label className="field">E-posta<input disabled value={user?.email??''} type="email"/></label><label className="field">İlçeniz<select name="district" defaultValue={user?.district}>{DISTRICTS.map((d)=><option key={d}>{d}</option>)}</select></label><div className="border-t pt-5"><h3 className="mb-4 flex items-center gap-2 text-sm font-semibold"><ShieldCheck size={17} className="text-primary"/>Şifre değiştir</h3><div className="grid gap-4 sm:grid-cols-2"><label className="field">Mevcut şifre<input name="currentPassword" type="password" autoComplete="current-password" maxLength={128}/></label><label className="field">Yeni şifre<input name="newPassword" type="password" autoComplete="new-password" minLength={10} maxLength={128} placeholder="En az 10 karakter"/></label></div><p className="mt-3 text-[11px] text-muted-foreground">Şifreni değiştirmek istemiyorsan bu alanları boş bırak.</p></div><ErrorBox message={error}/>{success&&<p role="status" className="text-sm text-chart-4">{success}</p>}<button disabled={busy} className="btn">{busy?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Değişiklikleri kaydet</button></form></div>;}
