import {NextResponse} from 'next/server';
import {z} from 'zod';
import {prisma} from '@/lib/db';
import {currentUser,unauthorized,apiError} from '@/lib/server';
import {DISTRICTS} from '@/lib/constants';
import {classify} from '@/lib/classify';
import {admitTicketRequest} from '@/lib/ticket-rate-limit';
import {Category,TicketStatus} from '@prisma/client';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const user=await currentUser();if(!user)return unauthorized();const p=new URL(req.url).searchParams;const status=p.get('status');const category=p.get('category');const district=p.get('district');const q=(p.get('q')??'').slice(0,100);const tickets=await prisma.ticket.findMany({where:{...(user.role==='MUNICIPAL_ADMIN'?{}:{userId:user.id}),...(status&&Object.values(TicketStatus).includes(status as TicketStatus)?{status:status as TicketStatus}:{}),...(category&&Object.values(Category).includes(category as Category)?{category:category as Category}:{}),...(district?{district}:{}),...(q?{OR:[{title:{contains:q}},{id:{contains:q}}]}:{})},select:{id:true,title:true,district:true,category:true,status:true,assignedDepartment:true,createdAt:true,aiConfidenceScore:true},orderBy:{createdAt:'desc'},take:200});return NextResponse.json(tickets);}catch(e){return apiError(e);}}
export async function POST(req:Request){try{const user=await currentUser();if(!user)return unauthorized();const parsed=z.object({title:z.string().trim().min(5).max(140),description:z.string().trim().min(20).max(5000),district:z.string().refine((v:string)=>DISTRICTS.includes(v)),neighborhood:z.string().trim().max(120).optional(),category:z.nativeEnum(Category),uploadIds:z.array(z.string().uuid()).max(3).default([])}).safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Başlık en az 5, açıklama en az 20 karakter olmalı. İlçe ve kategori seçimini kontrol edin.'},{status:400});const data=parsed.data;const files=await prisma.upload.findMany({where:{id:{in:data.uploadIds},userId:user.id,confirmed:true,ticketId:null}});if(files.length!==new Set(data.uploadIds).size)return NextResponse.json({error:'Fotoğraflar doğrulanamadı. Lütfen yeniden yükleyin.'},{status:400});
 const admission=await admitTicketRequest(user.id);if(!admission.allowed)return NextResponse.json({error:`Başvuru gönderim sınırına ulaştınız. Yaklaşık ${Math.ceil(admission.retryAfter/60)} dakika sonra tekrar deneyin. Mevcut başvurularınızı takip etmeye devam edebilirsiniz.`},{status:429,headers:{'Retry-After':String(admission.retryAfter),'Cache-Control':'no-store'}});
 const encoder=new TextEncoder();const stream=new ReadableStream({async start(controller){let open=true;const send=(value:unknown)=>{if(open){try{controller.enqueue(encoder.encode(`data: ${JSON.stringify(value)}\n\n`));}catch{open=false;}}};const timer=setInterval(()=>send({status:'processing',message:'Başvurunuz işleniyor…'}),7000);try{const result=await classify(data.title,data.description,data.district,(message:string)=>send({status:'processing',message}));const ticket=await prisma.$transaction(async(tx)=>{const item=await tx.ticket.create({data:{userId:user.id,title:data.title,description:data.description,district:data.district,neighborhood:data.neighborhood,selectedCategory:data.category,category:result.category,assignedDepartment:result.assignedDepartment,aiConfidenceScore:result.confidence,events:{create:{status:'OPEN',message:'Başvuru alındı ve ilgili birime yönlendirildi.'}}}});const linked=await tx.upload.updateMany({where:{id:{in:data.uploadIds},userId:user.id,ticketId:null,confirmed:true},data:{ticketId:item.id}});if(linked.count!==files.length)throw new Error('Fotoğraflar başka bir başvuruya bağlandı.');return item;});send({status:'completed',result:{id:ticket.id,...result}});}catch(e){console.error(e);send({status:'error',message:e instanceof Error?e.message:'Başvurunuz kaydedilemedi.'});}finally{clearInterval(timer);if(open)controller.close();}}});return new Response(stream,{headers:{'Content-Type':'text/event-stream','Cache-Control':'no-cache','X-Accel-Buffering':'no'}});
 }catch(e){return apiError(e);}}
